Menrva-pixel/Lost-and-found-finder

src/scripts/index.js
src/scripts/routes/routes.js
src/scripts/routes/url-parser.js
src/scripts/views/app.js
src/scripts/views/pages/about.js
src/scripts/views/pages/contact.js
src/scripts/views/pages/home.js

URL Routing

---

src/styles/style.css
src/templates/index.html

membuat footer

---

src/scripts/routes/routes.js
src/scripts/views/components/function-section.js
src/scripts/views/components/informationSection.js
src/scripts/views/pages/found-form.js
src/scripts/views/pages/home.js
src/scripts/views/pages/lost-form.js
src/styles/style.css

Nambahin route buat halaman lost form dan found form, plus perbaiki tab pake eslint.

Adding routes + eslint fix

---

src/scripts/index.js
src/scripts/routes/routes.js
src/scripts/views/app.js
src/scripts/views/components/_site-description-element.js
src/scripts/views/components/informationSection.js
src/scripts/views/pages/lostitems.js
src/scripts/views/template/template-creator.js
src/styles/search-bar.css
src/styles/style.css

Buat routing untuk halaman yang nampilin semua barang yang hilang

Create Routing for Lost Items Page

---

src/scripts/views/pages/lostitems.js
src/scripts/views/template/template-creator.js
src/styles/responsive.css
src/styles/style.css

Tambahin filter dan perbaiki layout card

Perbaiki Halaman Lost Items

---

src/scripts/views/pages/about.js
src/styles/responsive.css
src/styles/style.css

memperbaiki tampilan information section dan about page ketika di tampilan smartphone

information-section dan about page

---

src/styles/app-bar.css
src/styles/menu-button.css
src/styles/responsive.css
src/templates/index.html

Perbaiki tombol hamburger yang kegedean, sidebar fix abt-btn biar gak aneh pas animasi.

Fix Menu Button and Sidebar

---

src/scripts/utils/scrollbutton-initiator.js
src/scripts/views/components/_information-section.js
src/scripts/views/pages/home.js
src/styles/responsive.css
src/styles/style.css

menambahkan button scroll di informasi kehilangan di tampilan desktop dan memperbaiki sedikit tampilan function-section di tampilan desktop dan tablet agar terlihat lebih baik

menambahkan button scroll di informasi kehilangan

---

src/scripts/views/app.js
src/scripts/views/components/_hero-element.js
src/scripts/views/pages/detail-item.js
src/styles/app-bar.css
src/styles/responsive.css
src/templates/index.html

Perbaiki fungsi tombol buat laporan, menambahkan event scroll to top saat ganti halaman, perbaiki gambar gak muncul, perbaiki responsive header.

Minor fix here and there

---

package-lock.json
src/scripts/views/components/_footer-element.js
src/scripts/views/components/_found-form.js
src/scripts/views/components/_function-section.js
src/scripts/views/components/_hero-element.js
src/scripts/views/components/_information-section.js
src/scripts/views/components/_lost-form.js
src/scripts/views/components/_services-element.js
src/scripts/views/components/_site-description-element.js
src/scripts/views/pages/found-item-service.js
src/scripts/views/pages/lost-item-service.js
src/styles/_banner.css
src/styles/_form.css
src/styles/app-bar.css
src/styles/responsive.css
src/styles/style.css
src/templates/index.html

Reverts Menrva-pixel/Lost-and-found-finder#40
revert back to previous merge due to bugs

Revert "Mengupdate Navbar, Home, Footer, Lost-item Service dan Found-item Ser…"

---

src/styles/_banner.css

Perbaiki font size (responsive) di banner form

Fix Font Size Banner Form

---

src/scripts/views/components/_found-form.js
src/scripts/views/components/_lost-form.js
src/scripts/views/template/template-creator.js

Buat term of use jadi pop up/modal

New Pop Up TOU

---

src/styles/_sponsor.css
src/styles/credit.css

Merubah ukuran gambar, menengahkan title Sponsored By

Update laman about

---

src/scripts/views/components/_information-section.js
src/scripts/views/pages/home.js
src/styles/responsive.css
src/styles/style.css

menghilangkan scrollbar pada information section pada tampilan desktop

menghilangkan scrollbar information section

---

src/scripts/views/pages/about.js

Mengedit deskripsi about

---

src/scripts/data/lost-and-found-api.js
src/scripts/globals/api-endpoint.js
src/scripts/globals/config.js
src/scripts/utils/found-form-handler.js
src/scripts/utils/lost-form-handler.js
src/scripts/views/components/_found-form.js
src/scripts/views/pages/found-item-service.js
src/scripts/views/pages/list-item-service.js
src/scripts/views/pages/lost-item-service.js
src/scripts/views/template/template-creator.js

Update Backend, semoga gak error

Major Backend Update

---

src/scripts/views/components/_function-section.js
src/scripts/views/components/_hero-element.js
src/styles/style.css

Memberikan border radius pada button buat laporan, cari barang, lapor penemuan

Merubah style button

---

src/scripts/data/lost-and-found-api.js
src/scripts/globals/api-endpoint.js
src/scripts/utils/found-form-handler.js
src/scripts/utils/lost-form-handler.js
src/scripts/views/components/_found-form.js
src/scripts/views/components/_lost-form.js
src/scripts/views/pages/list-item-service.js
src/scripts/views/template/template-creator.js

update API Config dan Fix Loading while submitting

Update API Config

---

src/scripts/views/pages/list-item-service.js

Perbaiki fitur filter dan search biar berfungsi

Filter & Search Feature Works

---

src/scripts/views/components/_found-form.js
src/scripts/views/components/_hero-element.js
src/scripts/views/components/_lost-form.js
src/scripts/views/components/_services-element.js
src/scripts/views/components/_site-description-element.js
src/scripts/views/pages/found-item-service.js
src/styles/_banner.css
src/styles/_form.css
src/styles/style.css

Merubah style button, ukuran font site-description, style form penemuan barang, style form kehilangan barang

Merubah style home, lost-item-service, found-item-service

---

src/scripts/data/lost-and-found-api.js
src/scripts/routes/routes.js
src/scripts/views/pages/detail-item.js
src/scripts/views/template/template-creator.js

Detail Item Routing

---

src/scripts/views/template/template-creator.js
src/styles/style.css

list item style

---

src/styles/_services.css
src/styles/responsive.css

Barkah job

---

src/scripts/views/pages/detail-item.js
src/styles/style.css

detail page update

---

src/scripts/views/components/_information-section.js
src/scripts/views/template/template-creator.js

Membuat fungsi buat nampilin item terbaru pada landing page.

Update Information Section

---

src/styles/responsive.css
src/styles/style.css

responsif patch

---

src/scripts/views/pages/detail-item.js
src/styles/style.css

Buat detail item jadi beda antara lost or found

Update Detail Item

---

src/scripts/views/pages/about.js
src/styles/responsive.css
src/styles/style.css

Merubah position image menjadi absolute

Merubah tampilan card image

---

src/scripts/views/pages/list-item-service.js
src/styles/style.css

Sort item list berdasarkan postingan terbaru dan perbaiki sedikit tampilan card-nya

Fix Item List

---

src/styles/_form.css

Memberikan border-radius, merubah warna background dan button pada swal

Mengupdate style form

---

.eslintrc.json
package-lock.json
package.json
src/scripts/views/app.js
src/scripts/views/components/_function-section.js
src/scripts/views/components/_services-element.js
src/scripts/views/components/_site-description-element.js

animation added with AOS library

landing page animation update

---

src/scripts/views/pages/404.js

leftover patch

---

src/scripts/views/pages/list-item-service.js

Fix Halaman Reload saat filter item

Fix Halaman Reload

---

src/scripts/views/components/_found-form.js
src/scripts/views/components/_lost-form.js

Perbaiki form validation biar gak bisa submit kalau sudah upload foto saja. Coba di tes siapa tau ngebug.

Update Form Validation

---

.env
src/scripts/routes/routes.js
src/scripts/views/components/_services-element.js
src/scripts/views/pages/finder-profile.js
src/styles/_form.css
src/styles/responsive.css
src/styles/style.css

finder profile added
add fix / responsiveness to 1080p display

new page added

---

src/scripts/views/components/_hero-element.js
src/scripts/views/components/_information-section.js
src/scripts/views/pages/list-item-service.js
src/scripts/views/template/template-creator.js
src/styles/style.css

new item card and list UI / UX

Item Card rework

---

src/styles/_form.css
src/styles/style.css

item card responsif
form button border

minor patch

---

src/scripts/views/pages/about.js

Mengedit card

---

src/scripts/views/pages/about.js
src/styles/_sponsor.css
src/styles/credit.css
src/styles/responsive.css
src/styles/style.css

mengubah position div social media profile agar tetap di bawah

memperbaiki position social media profile

---

src/scripts/views/components/_found-form.js
src/scripts/views/components/_lost-form.js

security patch
